#!/bin/sh

NAME="$1"
TIME="$2"

if [ "$NAME" != "" ]; then
	IDX=$(uci -q show dhcp | grep "$NAME" |grep -oE "\[(\d+)\]")
	if [ "$IDX" != "" ];then
		MAC=$(uci -q get dhcp.@host$IDX.mac)
		if [ "$MAC" != "" ]; then
			uci -q add firewall rule
			uci -q set firewall.@rule[-1].src='lan'
			uci -q set firewall.@rule[-1].dest='wan' 
			uci -q set firewall.@rule[-1].proto='all'
			uci -q set firewall.@rule[-1].target='REJECT'
			uci -q set firewall.@rule[-1].src_mac="$MAC"
			if [ "$TIME" == "time" ]; then
				uci -q set firewall.@rule[-1].name="Bloqueio Time Telegram ${NAME}"
				uci -q set firewall.@rule[-1].start_time='23:00'
				uci -q set firewall.@rule[-1].stop_time='08:00'
				uci -q set firewall.@rule[-1].weekdays='mon tue wed thu fri sat sun'
			else
				uci -q set firewall.@rule[-1].name="Bloqueio Telegram ${NAME}"
			fi
			uci -q reorder firewall.@rule[-1]=1 
			uci -q commit firewall &> /dev/null
			/etc/init.d/firewall restart &> /dev/null
			if [ "$TIME" == "time" ]; then
				echo "New rule between 23:00 and 8:00 for ${NAME} created successfully !"
				else
				echo "New rule for ${NAME} created successfully !"
			fi
			exit 0
		fi
	fi
fi
echo "Error creating new rule ${NAME} !"
exit 1
