#!/bin/sh

for wifi in wlan0 wlan1
do
        if [ "${wifi}" == "wlan0" ]; then
                echo -en "--------------*${wifi} - 2.4 Ghz*--------------------\n"      
        else
                echo -en "--------------*${wifi} - 5 Ghz*----------------------\n"      
        fi
        macaddr=$(iwinfo ${wifi} assoclist |grep -oE "([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}" | awk '{printf $0 " "}')
        for lease in ${macaddr}
        do
                line=$(cat /tmp/dhcp.leases | grep -i ${lease})
                if [ $? == 0 ]; then
                        echo "${line}" | awk '{gsub( "*","\\*" ); gsub( "_","\\_" ); printf "Device: " $4 "\nIP: " $3 "\nMac: " toupper($2) "\nState: ";system("./get_ping "$4" 1");printf "\n"}'
                else
                        cat /proc/net/arp | grep -i ${lease} | awk '{gsub( "_","\\_" ); printf "IP: " $1 "\nMac: " toupper($4) "\nState: ";system("./get_ping "$1" 1");printf "\n"}'
                fi
                ./get_mac "${lease}"
                echo -e "=+=+=+=+=+=+=+=+=\n"
        done
        #echo -en "-----------------------------------------------------------\n"
done
