#!/bin/sh

mkdir /root/arps &>/dev/null

while [ true ] 
do

	for IP in $(cat /proc/net/arp | grep "192.168.250" | awk '{print $1}')
	do 
		LAST="NULL"	
		ping $IP -w 1 -q &>/dev/null 
		[ $? == 0 ]  && RESULT="UP" || RESULT="DOWN"
		if [ -e /root/arps/$IP ]; then
			LAST=$(cat /root/arps/$IP)
		fi
		if [ "${LAST}" != "${RESULT}" ];then
			name=$(cat /tmp/dhcp.leases | grep " ${IP} " | awk '{print $4}')
			[ "${name}" == "" ] && name=$(cat /tmp/hosts/dhcp | grep "^${IP}" | awk '{print $2}')
			date=$(date "+%d/%m/%Y %H:%M")
			telegram=$(echo "*Device:* ${name}"$'\n'"*Data:* ${date}"$'\n'"*IP:* ${IP}"$'\n'"*State:* ${RESULT}")
			/root/telebot "$telegram"		
		fi
		echo -en "${RESULT}" > /root/arps/$IP
	done 
	sleep 300
done&
