#!/bin/sh

export PATH="/usr/bin:/usr/sbin:/bin:/sbin"

source /root/variables

command="$1"

command_new=${command//_/\\_}

firewall=$(uci show firewall |grep "@rule" | grep name |grep -oE "\[[[:digit:]]+\].name='([[:graph:]]|[[:blank:]])+'" | awk -F ".name=" '{gsub(/[\047]|\[|\]/,"");print "[ {\"callback_data\": \""$1 "\" ,\"text\" : \"" $2 "\"} ],"}')
rules=${firewall:0:$((${#firewall}-1))}

keyboard='{"inline_keyboard": ['$rules'] }'

echo $keyboard

#curl -k -s -X POST -H "Charset: UTF-8"  $api/sendMessage -d chat_id=$my_chat_id -d "reply_markup=${keyboard}" -d "text=Choose one:"
