#!/bin/sh

source variables

command="$1"

command_new=${command//_/\\_}

curl -k -s -X POST $api/sendMessage -d chat_id=$sender -d parse_mode=Markdown --data-urlencode text="$command_new" &>/tmp/telegram.log
