#!/bin/sh

export PATH="/usr/bin:/usr/sbin:/bin:/sbin"

source /root/variables

command="$1"

command_new=${command//_/\\_}

rules=$(uci show firewall |grep "@rule" | grep name |grep -oE "\[[[:digit:]]+\].name='([[:graph:]]|[[:blank:]])+'" | awk -F ".name=" '{gsub("\\[|]","");print "[\""$1  " - " $2 "\"],"}')

keyboard='{"keyboard": ['$rules'["back"]],"one_time_keyboard": true}'

echo $keyboard

curl -k -s -X POST -H "Charset: UTF-8"  $api/sendMessage -d chat_id=$my_chat_id -d "reply_markup=${keyboard}" -d "text=All rules in firewall"
