#!/bin/sh

PATH='/usr/bin:/usr/sbin:/bin:/sbin'

source /root/variables

touch  /tmp/bot_vars.sh
path="${PWD}"
plugins="${path}/plugins"
command_not_found="Sorry,
I only recognize *commands*.
Commands are words beginning with a slash.
Try it !
Send [/start](/start) to get my commands list."

while [ true ]
do 
	source /tmp/bot_vars.sh
	offset=$(($offset+1))
	status=0
	updates=$(curl -s -k -X GET $api/getUpdates?offset=$offset)
	status=$(jsonfilter -s "$updates" -e $.ok)
	if [ $status = 'true' ]; then
		update_ids=$(jsonfilter -s "$updates" -e $.result[*].update_id)
	
		for update_id in $update_ids
		do
			origin=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].message.from.id")
			msg_id=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].message.message_id")
			command=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].message.text")
			is_a_cmd=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].message.entities[*].type")
			curl -k -s -X POST $api/getChatMember -d chat_id=$origin -d user_id=$origin >> /tmp/user.log

			if [ "$origin" != "$my_chat_id" ];then
				curl -k -s -X POST $api/sendMessage -d reply_to_message_id=$msg_id -d chat_id=$origin -d parse_mode=Markdown --data-urlencode text="This is a Private bot." &> /tmp/telegram.log
				curl -k -s -X POST $api/leaveChat -d chat_id=$origin  &> /tmp/telegram.log
			else
				if [ "$is_a_cmd" ==  "bot_command" ]; then
					cmd=$(echo $command |  awk '{print $1}')
					prms=$(echo $command | awk '{$1=""; print $0}')
					parms=${prms//[\"\&\;\\\>\<\|]/}			
					if [ -f "${plugins}$cmd" ]; then
						cd ${plugins}
						command=$("./$cmd" $parms)
						curl -k -s -X POST $api/sendMessage -d chat_id=$origin -d parse_mode=Markdown --data-urlencode text="$command" &> /tmp/telegram.log
						cd  ${path}
					else
						curl -k -s -X POST $api/sendMessage -d chat_id=$origin -d parse_mode=Markdown --data-urlencode text="Command *${cmd}* not found!" &> /tmp/telegram.log
					fi
				else
					curl -k -s -X POST $api/sendMessage -d reply_to_message_id=$msg_id -d chat_id=$origin -d parse_mode=Markdown --data-urlencode text="${command_not_found}" &> /tmp/telegram.log
				fi
			fi
		done
	
		if [ -n "$update_ids" ]; then
			echo "offset=$update_id" > /tmp/bot_vars.sh
	  	fi
	fi
	sleep 1
done&
