#!/bin/sh

RULE_NUM="$1" 
RULE_NAME="$2"

if [ "$RULE_NUM" == "" ]; then
	echo "1|Rule Num Error!!"
	return 1
else
	uci -q delete firewall.@rule${RULE_NUM}
	uci -q commit firewall &> /dev/null
	/etc/init.d/firewall restart &> /dev/null
	echo "1|Rule $RULE_NAME deleted!"
	return 0
fi
