#!/bin/sh

RULE_NUM="$1"
RULE_NAME="$2" 

if [ "$RULE_NUM" == "" ]; then
	echo "1|Rule Num Error!!"
	return 1
else
	uci -q set firewall.@rule[$RULE_NUM].enabled='1'
	uci -q commit firewall &> /dev/null
	/etc/init.d/firewall restart &> /dev/null
	echo "1|rule $RULE_NAME is enabled."
	exit 0
fi
