#!/bin/sh

IFACE="$1"

if [ "$IFACE" == "" ]; then
	echo "1|Network interface dont exist !!"
	return 1
else
	uci -q set network.$IFACE.disabled='1'
	uci -q commit network &> /dev/null
	/sbin/ifdown $IFACE &> /dev/null
	echo "1|Network Interface $IFACE is disabled."
	exit 0
fi
