#!/bin/sh

RULE_NUM="$1"
RULE_NAME="$2" 

if [ "$RULE_NUM" == "" ]; then
	echo "1|Rule Num Error!!"
	return 1
fi

/etc/init.d/proxy stop &> /dev/null

if [ "$RULE_NUM" == "0" ]; then
	uci -q set telegramopenwrt.proxy.config.http=false
elif [ "$RULE_NUM" == "1" ]; then
	uci -q telegramopenwrt.proxy.config.https=false
elif [ "$RULE_NUM" == "2" ]; then
	uci -q telegramopenwrt.proxy.config.http=false
	uci -q telegramopenwrt.proxy.config.https=false
fi
uci -q commit proxy &> /dev/null
echo "1|Proxy $RULE_NAME is stopped."
exit 0
