#!/bin/sh
RULE_NUM="$1"
RULE_NAME="$2"
if [ "$RULE_NUM" == "" ]; then
	echo "1|Rule Num Error!!"
	return 1
else
	uci -q set wireless.radio$RULE_NUM.__toggle='Disable'
	uci -q set wireless.radio$RULE_NUM.disabled='1'
	uci -q commit wireless &> /dev/null
	/sbin/wifi &> /dev/null
	echo "1|Radio $RULE_NAME is disabled."
	exit 0
fi
