#!/bin/sh

RULE_NUM="$1" 
RULE_NAME="$2"

if [ "$RULE_NUM" == "" ]; then
	echo "Rule Num Error!!"
	return 1
else
	uci delete firewall.@rule${RULE_NUM}
	uci commit firewall &> /dev/null
	/etc/init.d/firewall restart &> /dev/null
	echo "Rule $RULE_NAME deleted!"
	return 0
fi
