#!/bin/sh

RULE_NUM="$1"
RULE_NAME="$2" 

if [ "$RULE_NUM" == "" ]; then
	echo "1|Rule Num Error!!"
	return 1
else
	uci set wireless.radio$RULE_NUM.__toggle='Enable'
	uci commit wireless &> /dev/null
	/sbin/wifi &> /dev/null
	echo "1|Radio $RULE_NAME is enabled."
	exit 0
fi
