#!/bin/sh

old=$IFS
IFS=$'\n'
TOTAL=0

echo "*Rules*"

for rule in $(uci show firewall  | grep rule )
do
	line=$(echo ${rule} | awk -F "." '{print $3}')
	new=${line//\'/}
	new2=${new//_/\\_}
	echo ${new2//\*/all}
done
IFS=$old
