#!/bin/sh

echo -en "I can help you to manage and get some informations about your OpenWRT Router.\nThis is the avaliable commands list:\n\n"
ALLPLUGINS=$(ls -1 -p | grep -v "/")
for plug in $ALLPLUGINS
do
help=$(cat "help/${plug}")
echo "[/${plug}](/${plug}) - ${help}"
done
