#!/bin/sh

old=$IFS
IFS=$'\n'
TOTAL=0

echo "*Wireless*"

for rule in $(uci show wireless  | grep "@wifi-iface" )
do
	line=$(echo ${rule} | awk -F "." '{print $3}')
	id=$(echo ${rule} | grep ".name" | grep -oE "\[[[:digit:]]+\]" | awk '{gsub("\\[|]","");printf $1}')
	if [ "$id" != "" ]; then
		echo "id: $id"
	fi
	new=${line//\'/}
	new2=${new//_/\\_}
	new3=${new2//=/: }
	echo ${new3//\*/all}
done
IFS=$old
