#!/bin/sh

for wifi in wlan0 wlan1
do
	macaddr=$(iw dev ${wifi} station dump | grep Station | grep -oE "([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}" | awk '{printf $0 " "}')
	for lease in ${macaddr}
	do
		if [ "${wifi}" == "wlan0" ]; then
			echo -en "Wifi: 2.4Ghz\n"
		else
			echo -en "Wifi: 5Ghz\n"
		fi
		cat /tmp/dhcp.leases | grep ${lease} | awk '{gsub( "_","\\_" ); printf "Device: " $4 "\nIP: " $3 "\nMac: " toupper($2) "\n"}'
		./get_mac "${lease}"
		echo -en "\n"
	done
done

