#!/bin/sh

export PATH="/usr/bin:/usr/sbin:/bin:/sbin"

url=$(uci -q get telegramopenwrt.global.url)
key=$(uci -q get telegramopenwrt.global.key)
api="$url$key"
my_chat_id=$(uci -q get telegramopenwrt.global.my_chat_id)

#"text":"\u27a1\ufe0f" >
#"text":"\u2b05\ufe0f" <
#"text":"\u2b06\ufe0f" ^
#"text":"\u2b07\ufe0f" D^
#"text":"\u2197\ufe0f" U> 
#"text":"\u2198\ufe0f" D> 
#"text":"\u2199\ufe0f" D< 
#"text":"\u2196\ufe0f" U< 

# command: 
# 1 -> para camera
# 2 -> cima
# 0 -> baixo
# 4 -> direita
# 6 -> esquerda
# 92 -> cima direita
# 93 -> cima esquerda
# 91 -> baixo esquerda
# 90 -> baixo direita
# 25 -> movimenta todos lados.

keyboard='{"keyboard": [["\u2196\ufe0f","\u2b06\ufe0f","\u2197\ufe0f"],["\u2b05\ufe0f","O","\u27a1\ufe0f"],["\u2199\ufe0f","\u2b07\ufe0f", "\u2198\ufe0f"]],"one_time_keyboard": true}'

curl -k -s -X POST -H "Charset: UTF-8"  $api/sendMessage -d chat_id=$my_chat_id -d "reply_markup=${keyboard}" -d "text=Now move the camera, to stop send /cam_mv"
