#!/bin/ash

export PATH='/usr/bin:/usr/sbin:/bin:/sbin'

has_offer=0
count=0

(logread -f |while read line; do
	echo "${line}" | grep -q "ag71xx-mdio.0:00: Port"
	if [ $? == 0 ]; then
		ports=$(echo "${line}" | grep -oE "Port ([0-9]+) is (up|down)")
		date=$(echo "${line}" | grep -oE "^[a-zA-Z]+[[:space:]]+[a-zA-z]+[[:space:]]+[0-9]+[[:space:]]+[0-9:]+ [0-9]+")
		pnum=$(echo "${ports}" | cut -d ' ' -f 2)	
		state=$(echo "${ports}" | cut -d ' ' -f 4)	
		telegram=$(echo "*Port:* ${pnum}"$'\n'"*Data:* ${date}"$'\n'"*State:* ${state}")
		/sbin/telebot "$telegram"
	fi
	echo "${line}" | grep -q "DHCPOFFER" 
	if [ $? == 0 ]; then
		has_offer=1
		count=4
	fi

	echo "${line}" | grep -q "DHCPACK" 
	if [ $? == 0 ] && [ $has_offer == 1 ]; then 
		dados=$(echo "${line}" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} \w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2} .*")
		if [ "${dados}" == "" ];then
			dados=$(echo "${line}" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} \w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2}")
		fi
		date=$(echo "${line}" | grep -oE "^[a-zA-Z]+[[:space:]]+[a-zA-z]+[[:space:]]+[0-9]+[[:space:]]+[0-9:]+ [0-9]+")
		ip=$(echo "${dados}" | cut -d ' ' -f 1)
		macaddr=$(echo "${dados}" | cut -d ' ' -f 2)
		name=$(echo "${dados}" | cut -d ' ' -f 3 | awk '{gsub("*","\*"); gsub( "_","\_" );  printf $0 }')
		if [ "${name}" == "" ];then
			name="\*"
		fi
		ignored_macaddrs_file=$(uci -q get telegramopenwrt.global.ignored_macaddrs_file)
		if ! grep -q "$macaddr" $ignored_macaddrs_file; then
			telegram=$(echo "*Device:* ${name}"$'\n'"*Data:* ${date}"$'\n'"*IP:* ${ip}"$'\n'"*MACADDR:* ${macaddr}")
			/sbin/telebot "$telegram"
			has_offer=0
		else
			echo "Ignored macaddr found in ignore list"
		fi
	fi
	if [ $count == 0 ]; then
		has_offer=0
	else
		count=$((count-1))
	fi
done)&
