#!/bin/sh

export PATH='/usr/bin:/usr/sbin:/bin:/sbin'

url=$(uci get telegramopenwrt.global.url)
key=$(uci get telegramopenwrt.global.key)
api="$url$key"
my_chat_id=$(uci get telegramopenwrt.global.my_chat_id)

command="$1"

command_new=${command//_/\\_}

curl -k -s -X POST $api/sendMessage -d chat_id=$my_chat_id -d parse_mode=Markdown --data-urlencode text="$command_new" &>/tmp/telegram.log
