#!/bin/sh

PATH='/usr/bin:/usr/sbin:/bin:/sbin'

url=$(uci get telegramopenwrt.global.url)
key=$(uci get telegramopenwrt.global.key)
api="$url$key"
my_chat_id=$(uci get telegramopenwrt.global.my_chat_id)


while [ true ] 
do
	curl -k -X POST $api/sendChatAction -d "chat_id=$my_chat_id" -d "action=typing" &> /tmp/telegram.log   
	echo "Typing"
	sleep 6
done
