#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=95
STOP=15

USE_PROCD=1
PROG=/sbin/telegram_bot
CONFIGURATION=telegramopenwrt

start_service () {
        PID=$(pgrep -f ${PROG})
        if [ -z "$PID" ]  ; then
                config_load "${CONFIGURATION}"

                procd_open_instance
                procd_set_param command /bin/sh "$PROG"
                procd_set_param file /etc/config/telegramopenwrt
                procd_set_param stdout 1
                procd_set_param stderr 1
                procd_close_instance
        fi
}

stop_service() {
        pids=$(pgrep -f ${PROG} | xargs echo)
        for i in $pids; do extra_pids="${extra_pids} $(pgrep -P $i | xargs echo)"; done;
        kill $(echo "${extra_pids} ${pids}") 2> /dev/null
}
