#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=95
STOP=15

boot(){
return 0
}

start() {
/root/host_scan
}

stop() {
pids=$(pgrep -f host_scan | xargs echo)
for i in $pids; do extra_pids="${extra_pids} $(pgrep -P $i | xargs echo)"; done;
kill $(echo "${extra_pids} ${pids}") 2> /dev/null
return 0                                         
}       
 
restart(){
stop      
sleep 1
start  
}  
