#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2014 OpenWrt.org

START=95
STOP=15

SERVICE_USE_PID=1

boot() {
	return
}

start() {
	service_start /root/telegram_bot
}

stop() {
	kill $(pgrep -f telegram_bot)
}
